#  _     _     _ _   _          _____
# | |   | |   (_) | | |        |  __ \
# | |__ | |__  _| |_| |_ ______| |__) |___ _ __ ___   _____   _____ _ __
# | '_ \| '_ \| | __| __|______|  _  // _ \ '_ ` _ \ / _ \ \ / / _ \ '__|
# | | | | | | | | |_| |_       | | \ \  __/ | | | | | (_) \ V /  __/ |
# |_| |_|_| |_|_|\__|\__|      |_|  \_\___|_| |_| |_|\___/ \_/ \___|_|
# Useful!
# hhitt-Remover documentation: https://hhitt-1.gitbook.io/hhitt-remover-documentation
# discord server for support or suggestions: https://discord.com/invite/y9Gz42VPZC
# messages only support legacy color codes due to are quite simple.

messages:
  config-reloaded: "&bhhitt-Remover reloaded successfully!"
  no-permission: "&cYou don't have permission to perform that!"
  no-such-command: "&cNo such command!"

# If this option is enabled, in the regions where "hhitt-remover" flag is enabled
# players will not be able to place blocks that are not listed in "blocks". Same goes for entities.
flag-limit-placing: true

# In the following section you can define the worlds where you want to remove blocks and entities.
# "example-world" and "my-boxpvp" are the names of the worlds.
# Also, u need to allow "hhitt-remover" flag in the WorldGuard regions that plugin should work.
cleaner:
  example-world:
    blocks:
      glowstone: 15
      obsidian: 10
      dirt: 5
      cobweb: 30
    entities:
      ender_crystal: 10
  my-boxpvp:
    blocks:
      cobweb: 30
      white_wool: 10