name: hhittRemover
version: '2.1.0'
main: hhitt.org.example.hhittremover.HhittRemover
api-version: '1.20'
author: hhitt
depend: [WorldGuard]
commands:
  hhittremover-reload:
    description: reload the config.
    usage: /<command>
    permission: hhittremover.admin
