name: hhitt-remover
version: '1.0-SNAPSHOT'
main: dev.smartshub.hhittRemover.HhittRemover
api-version: '1.18'
authors: [ hhitt ]
commands:
  hhittremover:
    description: Reload the plugin
    usage: /hhittremover
    aliases: [ hr, remover ]
